import { describe, it, expect, beforeEach, vi } from "vitest";
import {
  generateMarkdownReport,
  generateHTMLReport,
  downloadReport,
  captureScreenshot,
} from "../../renderer/lib/report";

// ==================== Mock Data ====================

function createMockReportData() {
  return {
    scene: {
      metadata: {
        title: "自由落体实验",
        description: "研究物体在重力作用下的运动规律",
        subject: "Physics",
        difficulty: "Medium",
        grade: "10",
        topic: "free_fall",
      },
      entities: [{ position: [0, 10, 0], properties: { mass: 2 } }],
      environment: [{ type: "gravity_field", properties: { acceleration: 9.8 } }],
      equations: [
        { name: "位移公式", expression: "y = h - 0.5*g*t^2", type: "motion", variables: {}, is_solution: false },
      ],
      knowledge_tags: [
        { id: "kp1", name: "重力加速度", learning_tips: "地球表面约为 9.8 m/s^2", category: "力学", common_mistakes: ["忽略空气阻力"] },
      ],
      teacher_steps: [
        { titleKey: "释放小球", descKey: "从静止开始", order: 1, timeStart: 0, formulaKey: null },
      ],
      forces: [],
      timeline: { total_duration: 2, fps: 60, events: [] },
      simulation: {
        params: { h0: 10, g: 9.8, m: 2 },
        equations: {
          y: "h0 - 0.5 * g * t * t",
          v: "-g * t",
          ke: "0.5 * m * v * v",
          pe: "m * g * y",
          total_e: "ke + pe",
        },
      },
    } as any,
    params: { mass: 2, gravity: 9.8, height: 10 },
    currentTime: 1.5,
    ballY: 8.9,
    ballVelocity: -14.7,
  };
}

// ==================== generateMarkdownReport ====================

describe("generateMarkdownReport", () => {
  it("应生成中文报告（zh-CN）", () => {
    const data = createMockReportData();
    const result = generateMarkdownReport(data, "zh-CN");
    expect(result).toContain("# Physics Lab 实验报告");
    expect(result).toContain("自由落体实验");
    expect(result).toContain("实验概述");
    expect(result).toContain("实验参数");
    expect(result).toContain("当前状态");
    expect(result).toContain("公式");
    expect(result).toContain("知识点");
    expect(result).toContain("教学步骤");
    expect(result).toContain("由 Physics Lab 自动生成");
  });

  it("应生成英文报告（en）", () => {
    const data = createMockReportData();
    const result = generateMarkdownReport(data, "en");
    expect(result).toContain("# Physics Lab Experiment Report");
    expect(result).toContain("Overview");
    expect(result).toContain("Parameters");
    expect(result).toContain("Current State");
    expect(result).toContain("Formulas");
    expect(result).toContain("Knowledge Points");
    expect(result).toContain("Teaching Steps");
    expect(result).toContain("Generated by Physics Lab");
  });

  it("应包含正确的参数表格", () => {
    const data = createMockReportData();
    const result = generateMarkdownReport(data, "zh-CN");
    expect(result).toContain("| 初始高度 h₀ | 10 | m |");
    expect(result).toContain("| 重力加速度 g | 9.8 | m/s² |");
    expect(result).not.toContain("| mass |");
  });

  it("应包含当前状态数值", () => {
    const data = createMockReportData();
    const result = generateMarkdownReport(data, "zh-CN");
    expect(result).toContain("(t = 1.50 s)");
    expect(result).toContain("位置 y");
    expect(result).toContain("8.90 m");
    expect(result).toContain("速度 v");
    expect(result).toContain("-14.70 m/s");
  });

  it("应包含公式和知识点详情", () => {
    const data = createMockReportData();
    const result = generateMarkdownReport(data, "zh-CN");
    expect(result).toContain("位移公式");
    expect(result).toContain("y = h − 0.5·g·t²");
    expect(result).toContain("重力加速度");
    expect(data.scene.knowledge_tags[0].learning_tips && result.includes(data.scene.knowledge_tags[0].learning_tips)).toBe(true);
  });

  it("教学步骤应根据 currentTime 显示完成状态", () => {
    const data = createMockReportData();
    // timeStart=0, currentTime=1.5 >= 0 → 应显示 ✓
    const result = generateMarkdownReport(data, "zh-CN");
    expect(result).toContain("✓");
  });
});

// ==================== generateHTMLReport ====================

describe("generateHTMLReport", () => {
  it("应返回有效的 HTML 字符串", () => {
    const data = createMockReportData();
    const html = generateHTMLReport(data, "zh-CN");
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("<html");
    expect(html).toContain("</html>");
    expect(html).toContain("<head>");
    expect(html).toContain("<body>");
  });

  it("中文 locale 应设置 lang=zh", () => {
    const data = createMockReportData();
    const html = generateHTMLReport(data, "zh-CN");
    expect(html).toContain('lang="zh"');
  });

  it("英文 locale 应设置 lang=en", () => {
    const data = createMockReportData();
    const html = generateHTMLReport(data, "en");
    expect(html).toContain('lang="en"');
  });

  it("应包含内联 CSS 样式", () => {
    const data = createMockReportData();
    const html = generateHTMLReport(data, "zh-CN");
    expect(html).toContain("<style>");
    expect(html).toContain("</style>");
  });

  it("应包含 Markdown 报告内容", () => {
    const data = createMockReportData();
    const html = generateHTMLReport(data, "zh-CN");
    expect(html).toContain("Physics Lab 实验报告");
    expect(html).toContain("自由落体实验");
  });
});

// ==================== downloadReport ====================

describe("downloadReport", () => {
  let mockCreateObjectURL: ReturnType<typeof vi.fn>;
  let mockRevokeObjectURL: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    mockCreateObjectURL = vi.fn(() => "blob:http://fake-url");
    mockRevokeObjectURL = vi.fn();
    (global as any).URL.createObjectURL = mockCreateObjectURL;
    (global as any).URL.revokeObjectURL = mockRevokeObjectURL;
  });

  it("应创建 Blob 并触发下载", () => {
    downloadReport("test content", "test.md");

    expect(mockCreateObjectURL).toHaveBeenCalledOnce();
    // 验证 a 标签被创建、点击并清理
  });

  it("使用正确的 MIME 类型", () => {
    downloadReport("content", "file.md");
    const callArgs = mockCreateObjectURL.mock.calls[0][0] as Blob;
    expect(callArgs.type).toBe("text/markdown;charset=utf-8");
  });
});

// ==================== captureScreenshot ====================

describe("captureScreenshot", () => {
  beforeEach(() => {
    document.body.innerHTML = "";
    // jsdom 不实现 toDataURL，需要 mock
    HTMLCanvasElement.prototype.toDataURL = vi.fn(() => "data:image/png;base64,fakedata");
  });

  it("默认选择器 #physics-canvas 找不到时应返回 null", () => {
    const result = captureScreenshot();
    expect(result).toBeNull();
  });

  it("自定义选择器找不到时应返回 null", () => {
    const result = captureScreenshot("#nonexistent-canvas");
    expect(result).toBeNull();
  });

  it("找到 canvas 时应返回 PNG data URL", () => {
    // 注入一个测试 canvas
    const canvas = document.createElement("canvas");
    canvas.id = "physics-canvas";
    document.body.appendChild(canvas);

    const result = captureScreenshot();
    expect(result).not.toBeNull();
    expect(result?.startsWith("data:image/png")).toBe(true);
  });

  it("自定义选择器应正确匹配", () => {
    const canvas = document.createElement("canvas");
    canvas.id = "custom-canvas";
    document.body.appendChild(canvas);

    const result = captureScreenshot("#custom-canvas");
    expect(result).not.toBeNull();
  });
});

// ==================== S82: export quality ====================

describe("S82 export quality", () => {
  it("HTML 正文不含原始 Markdown 符号（# ** |）", () => {
    const data = createMockReportData();
    const html = generateHTMLReport(data, "zh-CN");
    const body = html.slice(html.indexOf("<body>"), html.indexOf("</body>"));
    expect(body).not.toMatch(/#{1,3}\s/);
    expect(body).not.toContain("**");
    expect(body).not.toContain("|---");
  });

  it("HTML 表格已转换为 <table> 元素", () => {
    const data = createMockReportData();
    const html = generateHTMLReport(data, "zh-CN");
    expect(html).toContain("<table>");
    expect(html).toContain("<th>");
  });

  it("i18n 键名解析为文案，不泄漏原始键名", () => {
    const data = createMockReportData();
    data.scene.teacher_steps.push({ titleKey: "menu.file", descKey: "menu.file.new", order: 2, timeStart: 0 } as never);
    const result = generateMarkdownReport(data, "zh-CN");
    expect(result).toContain("文件");
    expect(result).toContain("新建实验");
    expect(result).not.toContain("menu.file.new");
  });

  it("无内容的知识点不渲染（不留空壳）", () => {
    const data = createMockReportData();
    data.scene.knowledge_tags.push({ id: "kpEmpty", name: "空知识点", category: "力学", level: 1 } as never);
    const result = generateMarkdownReport(data, "zh-CN");
    expect(result).not.toContain("空知识点");
  });

});
