import { useMastery } from "./mastery.store";
import { useAchievements } from "./achievements.store";
import { useWrongAnswers } from "./wrong-answer.store";
import { pluginRegistry } from "./plugin-registry";

export interface LearningSummary {
  overallPercent: number;
  totalKPs: number;
  masteredKPs: number;
  experiments: Array<{
    id: string;
    name: string;
    percent: number;
    mastered: number;
    total: number;
  }>;
  achievements: Array<{
    title: string;
    unlocked: boolean;
  }>;
  wrongAnswers: {
    total: number;
    unreviewed: number;
  };
  streak: number;
  generatedAt: string;
}

export function generateLearningSummary(locale: string): LearningSummary {
  const mastery = useMastery.getState();
  const achievements = useAchievements.getState();
  const wrongAnswers = useWrongAnswers.getState();
  const plugins = pluginRegistry.list();
  const entries = mastery.getAll();

  const allKPs: string[] = [];
  const experimentStats: LearningSummary["experiments"] = [];

  for (const p of plugins) {
    const kps = p.getKnowledgePoints();
    const kpIds = kps.map((k) => p.id + ":" + k.id);
    allKPs.push(...kpIds);
    const mastered = kpIds.filter((id) => entries[id]?.mastered).length;
    experimentStats.push({
      id: p.id,
      name: p.name,
      percent: kpIds.length > 0 ? Math.round((mastered / kpIds.length) * 100) : 0,
      mastered,
      total: kpIds.length,
    });
  }

  // Calculate streak
  const dates = Object.values(entries)
    .filter((e) => e.lastAttempted)
    .map((e) => new Date(e.lastAttempted!).toDateString());
  const unique = [...new Set(dates)].sort().reverse();
  let streak = 0;
  const today = new Date().toDateString();
  if (unique[0] === today || unique[0] === new Date(Date.now() - 86400000).toDateString()) {
    streak = 1;
    for (let i = 1; i < unique.length; i++) {
      const d1 = new Date(unique[i - 1]);
      const d2 = new Date(unique[i]);
      if ((d1.getTime() - d2.getTime()) / 86400000 <= 1.5) streak++;
      else break;
    }
  }

  return {
    overallPercent: allKPs.length > 0
      ? Math.round((allKPs.filter((id) => entries[id]?.mastered).length / allKPs.length) * 100)
      : 0,
    totalKPs: allKPs.length,
    masteredKPs: allKPs.filter((id) => entries[id]?.mastered).length,
    experiments: experimentStats,
    achievements: achievements.getAll().map((a) => ({ title: a.title, unlocked: a.unlocked })),
    wrongAnswers: {
      total: wrongAnswers.getCount(),
      unreviewed: wrongAnswers.getUnreviewed().length,
    },
    streak,
    generatedAt: new Date().toISOString(),
  };
}

export function formatSummaryMarkdown(summary: LearningSummary, locale: string): string {
  const isZh = locale === "zh-CN";
  const lines: string[] = [];

  lines.push(isZh ? "# Physics Lab 学习总结" : "# Physics Lab Learning Summary");
  lines.push("");
  lines.push(isZh
    ? `**生成时间**: ${new Date(summary.generatedAt).toLocaleString()}`
    : `**Generated**: ${new Date(summary.generatedAt).toLocaleString()}`);
  lines.push("");

  // Overall progress
  lines.push(isZh ? "## 总体进度" : "## Overall Progress");
  lines.push("");
  lines.push(isZh
    ? `- 总体掌握度: **${summary.overallPercent}%**`
    : `- Overall Mastery: **${summary.overallPercent}%**`);
  lines.push(isZh
    ? `- 已掌握知识点: ${summary.masteredKPs}/${summary.totalKPs}`
    : `- Knowledge Points Mastered: ${summary.masteredKPs}/${summary.totalKPs}`);
  lines.push(isZh
    ? `- 连续学习天数: **${summary.streak}** 天`
    : `- Learning Streak: **${summary.streak}** days`);
  lines.push("");

  // Experiments
  lines.push(isZh ? "## 实验进度" : "## Experiment Progress");
  lines.push("");
  for (const exp of summary.experiments) {
    const bar = "█".repeat(Math.round(exp.percent / 10)) + "░".repeat(10 - Math.round(exp.percent / 10));
    lines.push(`- **${exp.name}**: ${bar} ${exp.percent}% (${exp.mastered}/${exp.total})`);
  }
  lines.push("");

  // Achievements
  lines.push(isZh ? "## 成就徽章" : "## Achievements");
  lines.push("");
  for (const a of summary.achievements) {
    lines.push(`- ${a.unlocked ? "✅" : "🔒"} ${a.title}`);
  }
  lines.push("");

  // Wrong answers
  lines.push(isZh ? "## 错题回顾" : "## Wrong Answer Review");
  lines.push("");
  lines.push(isZh
    ? `- 错题总数: ${summary.wrongAnswers.total}`
    : `- Total Wrong: ${summary.wrongAnswers.total}`);
  lines.push(isZh
    ? `- 待复习: ${summary.wrongAnswers.unreviewed}`
    : `- Unreviewed: ${summary.wrongAnswers.unreviewed}`);
  lines.push("");

  // Footer
  lines.push("---");
  lines.push(isZh
    ? "*由 Physics Lab 自动生成*"
    : "*Generated by Physics Lab*");

  return lines.join("\n");
}