import type { PhysicsScene } from "@physics-lab/shared";

export interface ReportData {
  scene: PhysicsScene;
  params: Record<string, number>;
  currentTime: number;
  ballY: number;
  ballVelocity: number;
}

export function generateMarkdownReport(data: ReportData, locale: string): string {
  const { scene, params, currentTime, ballY, ballVelocity } = data;
  const meta = scene.metadata;
  const isZh = locale === "zh-CN";

  const lines: string[] = [];

  lines.push(`# ${isZh ? "Physics Lab 实验报告" : "Physics Lab Experiment Report"}`);
  lines.push("");
  lines.push(`**${meta.title}** | ${isZh ? "生成时间" : "Generated"}: ${new Date().toISOString()}`);
  lines.push("");

  // Overview
  lines.push(`## ${isZh ? "实验概述" : "Overview"}`);
  lines.push("");
  lines.push(`- **${isZh ? "题目" : "Topic"}**: ${meta.title}`);
  if (meta.description) lines.push(`- **${isZh ? "描述" : "Description"}**: ${meta.description}`);
  lines.push(`- **${isZh ? "学科" : "Subject"}**: ${meta.subject}`);
  lines.push(`- **${isZh ? "难度" : "Difficulty"}**: ${meta.difficulty ?? "-"}`);
  lines.push(`- **${isZh ? "年级" : "Grade"}**: ${meta.grade ?? "-"}`);
  lines.push("");

  // Parameters
  lines.push(`## ${isZh ? "实验参数" : "Parameters"}`);
  lines.push("");
  lines.push("| " + (isZh ? "参数" : "Parameter") + " | " + (isZh ? "数值" : "Value") + " | " + (isZh ? "单位" : "Unit") + " |");
  lines.push("|------|------|------|");
  for (const [key, value] of Object.entries(params)) {
    lines.push(`| ${key} | ${value} | |`);
  }
  lines.push("");

  // Current state
  lines.push(`## ${isZh ? "当前状态" : "Current State"}`);
  lines.push("");
  lines.push(`- **${isZh ? "时间" : "Time"}**: ${currentTime.toFixed(2)} s`);
  lines.push(`- **${isZh ? "位置" : "Position"}**: y = ${ballY.toFixed(2)} m`);
  lines.push(`- **${isZh ? "速度" : "Velocity"}**: v = ${ballVelocity.toFixed(2)} m/s`);
  lines.push("");

  // Equations
  if (scene.equations.length > 0) {
    lines.push(`## ${isZh ? "公式" : "Formulas"}`);
    lines.push("");
    for (const eq of scene.equations) {
      lines.push(`### ${eq.name}`);
      lines.push("");
      lines.push(`\`${eq.expression}\``);
      if (eq.is_solution) lines.push(` *(solution)*`);
      lines.push("");
    }
  }

  // Knowledge points
  if (scene.knowledge_tags.length > 0) {
    lines.push(`## ${isZh ? "知识点" : "Knowledge Points"}`);
    lines.push("");
    for (const kp of scene.knowledge_tags) {
      lines.push(`### ${kp.name}`);
      lines.push("");
      if (kp.learning_tips) lines.push(`💡 ${kp.learning_tips}`);
      if (kp.common_mistakes && kp.common_mistakes.length > 0) {
        lines.push("");
        lines.push(isZh ? "**常见错误**:" : "**Common Mistakes**:");
        for (const m of kp.common_mistakes) lines.push(`- ${m}`);
      }
      lines.push("");
    }
  }

  // Teacher steps
  if (scene.teacher_steps && scene.teacher_steps.length > 0) {
    lines.push(`## ${isZh ? "教学步骤" : "Teaching Steps"}`);
    lines.push("");
    for (const step of scene.teacher_steps.sort((a,b) => a.order - b.order)) {
      const checked = currentTime >= step.timeStart ? "✓" : "○";
      lines.push(`${checked} **${step.titleKey}** (t ≥ ${step.timeStart}s)`);
      lines.push(`  ${step.descKey}`);
      if (step.formulaKey) lines.push(`  \`${step.formulaKey}\``);
      lines.push("");
    }
  }

  lines.push("---");
  lines.push(`*${isZh ? "由 Physics Lab 自动生成" : "Generated by Physics Lab"}*`);

  return lines.join("\n");
}

export function downloadReport(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}


/** Capture Three.js canvas as PNG data URL */
export function captureScreenshot(): string | null {
  const canvas = document.querySelector("canvas");
  if (!canvas) return null;
  try { return canvas.toDataURL("image/png"); } catch { return null; }
}

/** Generate HTML report with embedded screenshot */
export function generateHTMLReport(data: ReportData, locale: string): string {
  const md = generateMarkdownReport(data, locale);
  const screenshot = captureScreenshot();
  const title = data.scene.metadata.title || "Experiment";
  return `<!DOCTYPE html>
<html lang="${locale === "zh-CN" ? "zh" : "en"}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>${title} - Physics Lab</title>
<style>
body{font-family:-apple-system,sans-serif;max-width:860px;margin:40px auto;padding:0 24px;color:#1e293b;line-height:1.7}
h1{font-size:28px;color:#0369a1;border-bottom:3px solid #0ea5e9;padding-bottom:12px;margin-bottom:20px}
h2{font-size:20px;color:#334155;margin:28px 0 12px;border-bottom:1px solid #e2e8f0;padding-bottom:6px}
img{max-width:100%;border-radius:12px;box-shadow:0 4px 20px rgba(0,0,0,.08);margin:16px 0}
code{background:#f1f5f9;padding:2px 6px;border-radius:4px;font-family:monospace;font-size:13px}
pre{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;overflow-x:auto;margin:12px 0}
pre code{background:none;padding:0}
table{border-collapse:collapse;width:100%;margin:12px 0}
th,td{border:1px solid #e2e8f0;padding:10px 14px;text-align:left}
th{background:#f8fafc;font-weight:600;color:#475569}
.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e2e8f0;color:#94a3b8;font-size:13px}
</style></head>
<body>
${screenshot ? `<img src="${screenshot}" alt="Screenshot" />\n` : ""}
${md}
<div class="footer">Generated by Physics Lab</div>
</body></html>`;
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
}
