import type { PhysicsScene } from "@physics-lab/shared";

export interface ReportData {
  scene: PhysicsScene;
  params: Record<string, number>;
  currentTime: number;
  ballY: number;
  ballVelocity: number;
}

export function generateMarkdownReport(data: ReportData, locale: string): string {
  const { scene, params, currentTime, ballY, ballVelocity } = data;
  const meta = scene.metadata;
  const isZh = locale === "zh-CN";

  const lines: string[] = [];

  lines.push(`# ${isZh ? "Physics Lab 实验报告" : "Physics Lab Experiment Report"}`);
  lines.push("");
  lines.push(`**${meta.title}** | ${isZh ? "生成时间" : "Generated"}: ${new Date().toISOString()}`);
  lines.push("");

  // Overview
  lines.push(`## ${isZh ? "实验概述" : "Overview"}`);
  lines.push("");
  lines.push(`- **${isZh ? "题目" : "Topic"}**: ${meta.title}`);
  if (meta.description) lines.push(`- **${isZh ? "描述" : "Description"}**: ${meta.description}`);
  lines.push(`- **${isZh ? "学科" : "Subject"}**: ${meta.subject}`);
  lines.push(`- **${isZh ? "难度" : "Difficulty"}**: ${meta.difficulty ?? "-"}`);
  lines.push(`- **${isZh ? "年级" : "Grade"}**: ${meta.grade ?? "-"}`);
  lines.push("");

  // Parameters
  lines.push(`## ${isZh ? "实验参数" : "Parameters"}`);
  lines.push("");
  lines.push("| " + (isZh ? "参数" : "Parameter") + " | " + (isZh ? "数值" : "Value") + " | " + (isZh ? "单位" : "Unit") + " |");
  lines.push("|------|------|------|");
  for (const [key, value] of Object.entries(params)) {
    lines.push(`| ${key} | ${value} | |`);
  }
  lines.push("");

  // Current state
  lines.push(`## ${isZh ? "当前状态" : "Current State"}`);
  lines.push("");
  lines.push(`- **${isZh ? "时间" : "Time"}**: ${currentTime.toFixed(2)} s`);
  lines.push(`- **${isZh ? "位置" : "Position"}**: y = ${ballY.toFixed(2)} m`);
  lines.push(`- **${isZh ? "速度" : "Velocity"}**: v = ${ballVelocity.toFixed(2)} m/s`);
  lines.push("");

  // Equations
  if (scene.equations.length > 0) {
    lines.push(`## ${isZh ? "公式" : "Formulas"}`);
    lines.push("");
    for (const eq of scene.equations) {
      lines.push(`### ${eq.name}`);
      lines.push("");
      lines.push(`\`${eq.expression}\``);
      if (eq.is_solution) lines.push(` *(solution)*`);
      lines.push("");
    }
  }

  // Knowledge points
  if (scene.knowledge_tags.length > 0) {
    lines.push(`## ${isZh ? "知识点" : "Knowledge Points"}`);
    lines.push("");
    for (const kp of scene.knowledge_tags) {
      lines.push(`### ${kp.name}`);
      lines.push("");
      if (kp.learning_tips) lines.push(`💡 ${kp.learning_tips}`);
      if (kp.common_mistakes && kp.common_mistakes.length > 0) {
        lines.push("");
        lines.push(isZh ? "**常见错误**:" : "**Common Mistakes**:");
        for (const m of kp.common_mistakes) lines.push(`- ${m}`);
      }
      lines.push("");
    }
  }

  // Teacher steps
  if (scene.teacher_steps && scene.teacher_steps.length > 0) {
    lines.push(`## ${isZh ? "教学步骤" : "Teaching Steps"}`);
    lines.push("");
    for (const step of scene.teacher_steps.sort((a,b) => a.order - b.order)) {
      const checked = currentTime >= step.timeStart ? "✓" : "○";
      lines.push(`${checked} **${step.titleKey}** (t ≥ ${step.timeStart}s)`);
      lines.push(`  ${step.descKey}`);
      if (step.formulaKey) lines.push(`  \`${step.formulaKey}\``);
      lines.push("");
    }
  }

  lines.push("---");
  lines.push(`*${isZh ? "由 Physics Lab 自动生成" : "Generated by Physics Lab"}*`);

  return lines.join("\n");
}

export function downloadReport(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
